post_install() {
    echo "==> Reloading udev rules..."
    udevadm control --reload
    echo "==> Enable and start service if needed:"
    echo "    systemctl enable --now vasak-impulse-daemon.service"
}

post_upgrade() {
    post_install
}

pre_remove() {
    systemctl --quiet is-active vasak-impulse-daemon.service && systemctl stop vasak-impulse-daemon.service 2>/dev/null
}

post_remove() {
    echo "==> Reloading udev rules..."
    udevadm control --reload
}
